import type { SplitHttpEditorState } from "../../lib/splitHttpConfigurator";
import { Field } from "../molecules/Field";
import { Input, Select, Textarea } from "../atoms/Input";
import { Switch } from "../atoms/Switch";

export function SplitHttpFields({ value, onChange }: { value: SplitHttpEditorState; onChange: (value: SplitHttpEditorState) => void }) {
  const set = (patch: Partial<SplitHttpEditorState>) => onChange({ ...value, ...patch });
  return <div className="splithttp-fields">
    <div className="configurator-grid"><Field label="Path"><Input value={value.path} onChange={(e) => set({ path: e.target.value })} placeholder="/packet" /></Field><Field label="Mode"><Select value={value.mode} onChange={(e) => set({ mode: e.target.value })}><option value="">Server default</option><option value="stream-one">stream-one</option><option value="packet-up">packet-up</option><option value="stream-up">stream-up</option><option value="auto">auto</option></Select></Field><Field label="Host overrides" hint="One host per line."><Textarea rows={3} value={value.hosts} onChange={(e) => set({ hosts: e.target.value })} /></Field><Field label="Headers" hint="One Name: value pair per line."><Textarea rows={3} value={value.headers} onChange={(e) => set({ headers: e.target.value })} /></Field><Field label="HTTP method"><Input value={value.method} onChange={(e) => set({ method: e.target.value })} /></Field><Field label="Uplink HTTP method"><Input value={value.uplinkHttpMethod} onChange={(e) => set({ uplinkHttpMethod: e.target.value })} placeholder="POST" /></Field></div>
    <h4>Padding</h4><div className="configurator-grid"><Field label="Padding form"><Select value={value.paddingKind} onChange={(e) => set({ paddingKind: e.target.value as SplitHttpEditorState["paddingKind"] })}><option value="none">Disabled</option><option value="fixed">Fixed bytes</option><option value="range">Range expression</option><option value="bounds">Explicit bounds</option></Select></Field>{value.paddingKind === "fixed" ? <Field label="Padding bytes"><Input type="number" value={value.paddingFixed} onChange={(e) => set({ paddingFixed: e.target.value })} /></Field> : null}{value.paddingKind === "range" ? <Field label="Padding range"><Input value={value.paddingRange} onChange={(e) => set({ paddingRange: e.target.value })} placeholder="100-1000" /></Field> : null}{value.paddingKind === "bounds" ? <>{([['paddingMin','Minimum'],['paddingMax','Maximum'],['paddingFrom','From'],['paddingTo','To']] as const).map(([key,label]) => <Field key={key} label={label}><Input type="number" value={value[key]} onChange={(e) => set({ [key]: e.target.value })} /></Field>)}</> : null}{([['paddingMethod','Padding method'],['paddingHeader','Padding header'],['paddingKey','Padding key'],['paddingPlacement','Padding placement']] as const).map(([key,label]) => <Field key={key} label={label}><Input value={value[key]} onChange={(e) => set({ [key]: e.target.value })} /></Field>)}</div>
    <h4>Upload placement</h4><div className="configurator-grid">{([['sessionPlacement','Session placement'],['sessionKey','Session key'],['seqPlacement','Sequence placement'],['seqKey','Sequence key'],['uplinkDataPlacement','Data placement'],['uplinkDataKey','Data key'],['uplinkChunkSize','Uplink chunk size'],['scMaxBufferedPosts','Buffered POST limit']] as const).map(([key,label]) => <Field key={key} label={label}><Input type={key.endsWith("Size") || key === "scMaxBufferedPosts" ? "number" : "text"} value={value[key]} onChange={(e) => set({ [key]: e.target.value })} /></Field>)}</div>
    <Switch checked={value.xmuxEnabled} onChange={(xmuxEnabled) => set({ xmuxEnabled })} label="Configure Xmux reuse limits" />{value.xmuxEnabled ? <div className="configurator-grid">{([['xmuxMaxConcurrency','Maximum concurrency'],['xmuxMaxConnections','Maximum connections'],['xmuxCMaxReuseTimes','Client reuse count'],['xmuxHMaxRequestTimes','HTTP request count'],['xmuxHMaxReusableSecs','Reusable lifetime (s)'],['xmuxHKeepAlivePeriod','Keep-alive period (s)']] as const).map(([key,label]) => <Field key={key} label={label}><Input type="number" value={value[key]} onChange={(e) => set({ [key]: e.target.value })} /></Field>)}</div> : null}
    <Switch checked={value.downloadEnabled} onChange={(downloadEnabled) => set({ downloadEnabled })} label="Override download-side transport" />{value.downloadEnabled ? <div className="configurator-grid"><Field label="Download network"><Select value={value.downloadNetwork} onChange={(e) => set({ downloadNetwork: e.target.value })}><option value="">Default</option>{["tcp","ws","httpupgrade","grpc","quic","kcp","splithttp"].map((item) => <option key={item}>{item}</option>)}</Select></Field><Field label="Download security"><Select value={value.downloadSecurity} onChange={(e) => set({ downloadSecurity: e.target.value })}><option value="">Default</option>{["none","tls","reality","shadowtls"].map((item) => <option key={item}>{item}</option>)}</Select></Field></div> : null}
  </div>;
}
